parameters:
  params_file_name:
    name: Parameters File
    format: String
    value: params.yml
  content_file_name:
    name: Content File
    format: String
    value: content.md
  output_file_name:
    name: Output File
    format: String
    value: output.html
  test_bool:
    name: Test Boolean
    format: Boolean
    value: true
  test_secret:
    name: Test Secret
    format: Secret
    value: 0bscured?