parameters:
  parametersFileName:
    name: Parameters File
    type: string
    secure: false
    value: params.yml
  contentFileName:
    name: Content File
    type: string
    value: content.md
  outputFileName:
    name: Output File
    type: string
    value: output.html