name: pogpen
settings:
- SubcommandRequiredElseHelp
subcommands:
    - render:
        about: render a set of files to a HTML output
        args:
            - PARAMETERS:
                index: 1
                help: parameters file (as YAML)
                required: true
            - CONTENT:
                index: 2
                help: content file (as Commonmark markdown)
                required: true
            - OUTPUT:
                index: 3
                help: destination file for rendered HTML
                required: true
